### PR TITLE
[DEPENDENCY]: updated ember-getowner-polyfill

### PR DESCRIPTION
**Pull request by toranb**
Removing the deprecation warning :)

### CODE REVIEW

**Comment by toranb** [comment]
@williamsbdev I'll need to revisit this tomorrow boss - some strange `service:-document` injection missing during a glimmer 2 dom dependency lookup (sounded strange 2 me also). I did upgrade to ember-cli v2.4.2 along the way to see if I had something else in the mix but no dice

**Comment by toranb** [comment]
@williamsbdev nevermind :) found the root cause was a missing visit in the acceptance tests! check this out /merge and publish when you have time this week

**Comment by williamsbdev** [comment]
@toranb - Thank you for taking the time to get this updated! Great work.

**Comment by williamsbdev** [comment]
@toranb - 1.1.1 has been tagged and published.

**Pull request merged**
